name = "log-system-worker"
main = "src/index.ts"
compatibility_date = "2024-11-10"

[vars]
GCP_LOG_NAME = "projects/streamerio-472706/logs/logsystem"
INGESTION_FAST_THRESHOLD = 25
REPLAY_MAX_BATCH = 50
default_environment = "development"


[[r2_buckets]]
binding = "DLQ_BUCKET"
bucket_name = "log-system-dlq"
